name: Script-Seed Actions
on: [pull_request]
jobs:

  lint:
    name: Lint (EditorConfig)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
